sudo: false

language: php

php:
  - 5.6

before_install:
  - composer self-update

script:
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
