sudo: false

language: php

php:
  - 5.6

before_install:
  - composer self-update

script:
  - phpunit

after_script:
  # Scrutinizer-CI.
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
